update horizen  operating step figure for UI
99cloud/lab-openstack pull request #27
Opened 2023-03-12 13:55 UTC by ChantYuCN

2023-03-13 01:11 UTC, wu-wenxiang requested changes

2023-03-13 01:11 UTC, wu-wenxiang commented on doc/class-01-OpenStack-Administration.md
> +    ```bash
这里应该是 console？

2023-03-13 01:11 UTC, wu-wenxiang commented on doc/class-01-OpenStack-Administration.md
> +    openstack endpoint list
$ openstack endpoint list

下面空一行

2023-03-13 01:11 UTC, wu-wenxiang commented on src/ansible-cloudlab-centos/README.md
> +    root@openstack:~# source /home/devstack/openrc admin admin
默认进 demo project，里面已经建好了 private network

2023-03-13 01:11 UTC, wu-wenxiang commented on doc/class-01-OpenStack-Administration.md
> +- 创建路由绑定 public 和 private 网路
默认进 demo project，private 网络和 router 都已经建好了。

这个是不是放到 neutron 章节更好？

2023-03-14 14:39 UTC, ChantYuCN commented on doc/class-01-OpenStack-Administration.md
> +    ```bash
thanks for remind 
已修改

2023-03-14 14:40 UTC, ChantYuCN commented on doc/class-01-OpenStack-Administration.md
> +    openstack endpoint list
thanks for remind
已修改

2023-03-14 14:44 UTC, ChantYuCN commented on src/ansible-cloudlab-centos/README.md
> +    root@openstack:~# source /home/devstack/openrc admin admin
thanks for remind
已修改

2023-03-14 15:07 UTC, ChantYuCN commented on doc/class-01-OpenStack-Administration.md
> +- 创建路由绑定 public 和 private 网路
thanks for remind 
已经把创建 router, 连接 public/private 的 step 放到 neutron 章节
另外 因为重复 我把原本的置换成新的

2023-03-15 01:33 UTC, wu-wenxiang approved these changes

2023-03-15 01:33 UTC, merged